### ISSUE TITLE
May I ask why didn't you compare your model with Co_DETR: DETRs with Collaborative Hybrid Assignments Training

### ISSUE THREAD

**Issue by trinhvg** [xiuqhou/Salience-DETR#31]
### Question

Dear authors,

Why did you not compare your model with Co_DETR: DETRs with Collaborative Hybrid Assignments Training?
I saw you mentioned it. I am curious why there are not many papers compared with  Co_DETR.

Thank you,

**Comment by xiuqhou** [comment]
Hello @trinhvg ,

Our focus of Salience-DETR is not to improve performance, but to reduce FLOPs as well. Co-DETR is a strong detector, we cannot beat it in performance, but we have faster inference speed and less FLOPs than it.

We think that only one of **performance** and **efficiency** is comparable, and it is meaningful to compare the other one. For example, we have the same performance as **DINO** but faster inference speed, we may say Salience-DETR suppresses DINO. But comparing Salience-DETR and Co-DETR can't get which one is better considering both performance and efficiency.

Another reason I guess why many papers don't compare their work with Co-DETR is that Co-DETR relies on faster CNN and ATSS architectures, which limits the application in many real-world tasks. The improvement of performance may come from the ensemble of several detectors, rather than a better design for DETR. I don't think this is a good and general choice to improve DETR.

**Comment by trinhvg** [comment]
Thank you for sharing your insight about this line of DETR,
It helps me a lot.
